# Generated by Django 5.1.4 on 2025-01-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_doctor_address_alter_doctor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Pediatrician', 'Pediatrician'), ('Orthopedic', 'Orthopedic'), ('Neurologist', 'Neurologist')], default='Cardiologist', max_length=50),
        ),
    ]
