# Generated by Django 5.1.4 on 2025-01-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_doctor_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
